// ═══════════════════════════════════════════════════════════════════
//   backend/services/hedera/thresholdAccount.mjs
//   ───────────────────────────────────────────────────────────────
//   The intermediary settlement account — where stablecoin from the
//   source-side partner lands before the destination-side partner
//   pulls it for payout. Its whole point is structural, not
//   promissory non-custody: this account's key is a Hedera KeyList
//   requiring BOTH partner signatures (2-of-2) to move funds out.
//   Neither partner alone, and critically, WE ourselves are not one
//   of the two keys — the platform never holds a signing key over
//   customer funds at any point in the flow.
//
//   In production, each side of this key pair would belong to the
//   source-side and destination-side licensed partner respectively
//   (e.g. their own custody infra — Hedera Stablecoin Studio lists
//   Zodia Custody and DFNS as real custody/wallet-infra providers
//   partners could use for exactly this). For this demo, since we
//   don't hold live partner credentials, we generate two ED25519
//   keypairs locally to STAND IN for "source partner key" and
//   "destination partner key" — clearly labeled as such. The account
//   creation and the 2-of-2 signing requirement on Hedera are real;
//   only the identity of the two key-holders is simulated.
//
//   Scaling note (documented, not built): a single intermediary
//   account works for a demo corridor. At volume, this pattern
//   extends to a rotating pool of N threshold-key accounts, each
//   capped at a transaction/value ceiling, to limit exposure and
//   avoid one account becoming a single, easily-surveilled
//   settlement hub. Out of scope for this MVP.
// ═══════════════════════════════════════════════════════════════════

import {
  PrivateKey,
  KeyList,
  AccountCreateTransaction,
  Hbar,
  TokenAssociateTransaction,
} from "@hashgraph/sdk";
import { getClient, getNetwork } from "./client.mjs";

let _cached = null;

/** Generates the two demo signer keypairs. In production these would
 *  never be generated by us — each would be supplied by the
 *  respective partner's own custody infrastructure. Logged clearly
 *  so it is never mistaken for a real partner credential. */
function generateDemoPartnerKeys() {
  const sourcePartnerKey = PrivateKey.generateED25519();
  const destinationPartnerKey = PrivateKey.generateED25519();
  console.warn(
    "[thresholdAccount] Generated DEMO keys standing in for the source-side " +
    "and destination-side partner. Replace with real partner-supplied public " +
    "keys before any non-demo use — see the file header for why."
  );
  return { sourcePartnerKey, destinationPartnerKey };
}

/** Creates (once) the 2-of-2 threshold-key intermediary account and
 *  associates it with the settlement stablecoin (USDC on Hedera —
 *  see corridorConfig.mjs for why USDC rather than EURC here).
 *  Cached in-process; in a real deployment this account is created
 *  once and its ID stored in .env, not re-created per transfer. */
export async function getOrCreateThresholdAccount({ usdcTokenId } = {}) {
  if (_cached) return _cached;

  if (process.env.INTERMEDIARY_ACCOUNT_ID) {
    // Already provisioned in a previous run — reuse it. The demo
    // signer keys are NOT recoverable from the account ID alone, so
    // if you're reusing an account created in a prior process, you
    // must also persist INTERMEDIARY_SOURCE_KEY / _DEST_KEY yourself.
    _cached = {
      accountId: process.env.INTERMEDIARY_ACCOUNT_ID,
      sourcePartnerKey: process.env.INTERMEDIARY_SOURCE_KEY
        ? PrivateKey.fromStringED25519(process.env.INTERMEDIARY_SOURCE_KEY)
        : null,
      destinationPartnerKey: process.env.INTERMEDIARY_DEST_KEY
        ? PrivateKey.fromStringED25519(process.env.INTERMEDIARY_DEST_KEY)
        : null,
      reused: true,
    };
    return _cached;
  }

  const client = getClient();
  const { sourcePartnerKey, destinationPartnerKey } = generateDemoPartnerKeys();

  // KeyList with threshold 2 of 2: BOTH keys must sign for any
  // transaction (transfer out, token association change, etc.)
  // against this account to succeed.
  const twoOfTwo = KeyList.of(
    sourcePartnerKey.publicKey,
    destinationPartnerKey.publicKey
  ).setThreshold(2);

  const createTx = await new AccountCreateTransaction()
    .setKey(twoOfTwo)
    .setInitialBalance(new Hbar(2)) // covers its own tiny fees (token association, etc.)
    .execute(client);
  const receipt = await createTx.getReceipt(client);
  const accountId = receipt.accountId.toString();
  const network = getNetwork();

  // Associate with the settlement stablecoin so it can actually hold
  // USDC once created — HTS requires explicit association before an
  // account can receive a given token. Signed by BOTH threshold keys.
  if (usdcTokenId) {
    const assocTx = await new TokenAssociateTransaction()
      .setAccountId(accountId)
      .setTokenIds([usdcTokenId])
      .freezeWith(client)
      .sign(sourcePartnerKey);
    const assocSigned = await assocTx.sign(destinationPartnerKey);
    const assocSubmit = await assocSigned.execute(client);
    await assocSubmit.getReceipt(client);
  }

  _cached = {
    accountId,
    sourcePartnerKey,
    destinationPartnerKey,
    hashscanUrl: `https://hashscan.io/${network}/account/${accountId}`,
    reused: false,
  };

  console.warn(
    `[thresholdAccount] Created intermediary account ${accountId} on ${network}. ` +
    `Save this as INTERMEDIARY_ACCOUNT_ID in .env to reuse it across restarts.`
  );

  return _cached;
}
