// ═══════════════════════════════════════════════════════════════════
//   backend/db/store.mjs
//   ───────────────────────────────────────────────────────────────
//   Replaces the local db.json file with real MongoDB persistence via
//   Prisma, while keeping the same readDb()/writeDb(data) shape the
//   rest of server.mjs already calls -- { transactions: {id: {...}},
//   communityPosts: [...] } -- so this migration doesn't require
//   rewriting every route individually, just swapping what's
//   underneath the same two functions.
//
//   IMPORTANT: this needs `npx prisma generate` run once in an
//   environment with real internet access (this project's own
//   sandbox during development could not reach
//   binaries.prisma.sh to download Prisma's engine -- a network
//   restriction specific to that sandbox, not a real limitation of
//   Prisma itself). Run it locally or let Render's build step run it
//   (add "prisma generate" to the build command) before this will
//   actually connect.
// ═══════════════════════════════════════════════════════════════════

import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DB_FILE = path.join(__dirname, '..', 'db.json');

async function readDbFromFile() {
  try {
    const data = await readFile(DB_FILE, 'utf8');
    return JSON.parse(data);
  } catch (e) {
    return { transactions: {}, communityPosts: [] };
  }
}

async function writeDbToFile(data) {
  await writeFile(DB_FILE, JSON.stringify(data, null, 2), 'utf8');
}

// Prisma's generated client isn't committed to git (it's a build
// artifact, regenerated by `npm run postinstall` / `prisma generate`).
// If it hasn't been generated yet in this environment, or MONGO_URI
// isn't set, fall back to the local JSON file rather than crashing
// the whole server on import -- this also means the existing test
// suite keeps working in environments that haven't run `prisma
// generate` (e.g. a sandbox with no network access to Prisma's own
// binary CDN), without silently pretending MongoDB is connected.
let prisma = null;
let usingMongo = false;
if (process.env.MONGO_URI) {
  try {
    const { PrismaClient } = await import('@prisma/client');
    prisma = new PrismaClient();
    usingMongo = true;
  } catch (e) {
    console.warn(
      '⚠️  MONGO_URI is set but the Prisma client is not available ' +
      '(run `npx prisma generate`). Falling back to local db.json for now:',
      e.message
    );
  }
} else {
  console.warn('⚠️  MONGO_URI not set. Using local db.json for now.');
}

function toTransactionRecord(row) {
  // Merge the explicitly-modeled columns back with whatever extra
  // fields were stashed in `raw`, so nothing added ad hoc elsewhere
  // in server.mjs gets silently dropped by having a schema.
  const { raw, id, ...columns } = row;
  return { id, ...columns, ...(raw || {}) };
}

export async function readDb() {
  if (!usingMongo) return readDbFromFile();

  const [transactions, communityPosts] = await Promise.all([
    prisma.transaction.findMany(),
    prisma.communityPost.findMany({ orderBy: { createdAt: 'desc' } }),
  ]);

  const transactionsById = {};
  for (const row of transactions) {
    transactionsById[row.id] = toTransactionRecord(row);
  }

  return {
    transactions: transactionsById,
    communityPosts: communityPosts.map((p) => ({
      id: p.postId,
      displayName: p.displayName,
      country: p.country,
      message: p.message,
      createdAt: p.createdAt.toISOString(),
    })),
  };
}

// The known, explicitly-modeled columns -- everything else on a
// transaction object goes into `raw` automatically, so a new field
// introduced in server.mjs later doesn't require a schema change to
// keep working, just won't be individually queryable until it is.
const KNOWN_COLUMNS = [
  'senderName', 'senderEmail', 'senderCountry', 'recipientName', 'recipientEmail',
  'recipientCountry', 'amount', 'currency', 'receivingCurrency', 'recipientAmount',
  'fee', 'exchangeRate', 'payoutMethod', 'purpose', 'status', 'complianceStatus',
  'settlementStatus', 'payoutStatus', 'estimatedDelivery', 'hederaTxRef',
  'hederaTopicId', 'hederaSequenceNumber', 'hederaConsensusTimestamp',
  'hederaTransactionHash', 'hashscanUrl', 'communityCodeHash',
];

export async function writeDb(data) {
  if (!usingMongo) return writeDbToFile(data);

  const txnWrites = Object.entries(data.transactions || {}).map(([id, txn]) => {
    const columns = {};
    const raw = {};
    for (const [key, value] of Object.entries(txn)) {
      if (key === 'id') continue;
      if (KNOWN_COLUMNS.includes(key)) columns[key] = value;
      else raw[key] = value;
    }
    if (columns.createdAt) columns.createdAt = new Date(columns.createdAt);
    if (columns.completedAt) columns.completedAt = new Date(columns.completedAt);
    if (columns.communityCodeIssuedAt) columns.communityCodeIssuedAt = new Date(columns.communityCodeIssuedAt);

    return prisma.transaction.upsert({
      where: { id },
      update: { ...columns, raw },
      create: { id, ...columns, raw },
    });
  });

  // Community posts are append-only in this app (no edits), so only
  // insert ones that don't already exist rather than upserting every
  // post on every write.
  const existingPostIds = new Set(
    (await prisma.communityPost.findMany({ select: { postId: true } })).map((p) => p.postId)
  );
  const postWrites = (data.communityPosts || [])
    .filter((p) => !existingPostIds.has(p.id))
    .map((p) =>
      prisma.communityPost.create({
        data: {
          postId: p.id,
          displayName: p.displayName,
          country: p.country || null,
          message: p.message,
          createdAt: p.createdAt ? new Date(p.createdAt) : new Date(),
        },
      })
    );

  await Promise.all([...txnWrites, ...postWrites]);
}

export async function closeDb() {
  if (prisma) await prisma.$disconnect();
}
